language: node_js
node_js:
  - "lts/*"
  - "10.5.0"

before_script:
  - npm install

script:
  - npm test

after_success:
  - npm run docs

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      node: "lts/*"