language: node_js
node_js:
  - "lts/*"

before_script:
  - npm install

script:
  - npm test
  - npm run cover

after_success:
  - npm run docs
  - npm pack

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      all_branches: true
      tags: true
      repo: CatalysmsServerManager/7-Days-to-Die-API-wrapper

  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "7daystodie-api-wrapper-*.tgz"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      repo: CatalysmsServerManager/7-Days-to-Die-API-wrapper

  - provider: npm
    skip_cleanup: true
    email: "niekcandaele@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
      all_branches: true
      repo: CatalysmsServerManager/7-Days-to-Die-API-wrapper