language: node_js
node_js:
  - "lts/*"
  - "8.11.3"
  - "10.5.0"

before_script:
  - npm install

script:
  - npm test

after_success:
  - npm run docs
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      node: "lts/*"
      tags: true

  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "7daystodie-api-wrapper-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "niekcandaele@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
      node: "lts/*"